### ISSUE TITLE
Sample Error: ERROR_THREAD_STATE_NOT_FOUND in Python App

### ISSUE THREAD

**Issue by rahulpowar** [Granulate/gprofiler#122]
I ran into an issue where I am not seeing the stack for a bunch of threads in a python 3 app under test. This is using the python BPF profiler running in a docker container alongside the python app running inside its own container. The main thread shows up but the rest seemed to be grouped under a ERROR_THREAD_STATE_NOT_FOUND sample with a few kernel samples.

![Screenshot 2021-06-23 at 20 02 45](https://user-images.githubusercontent.com/3083314/123279043-c9ad5780-d507-11eb-9728-c8107d1a82a5.png)

I don't see anything unusual in the agent logs apart from some reports of the below, not sure if it is related.

```
[15:11:26] Running global perf...
[15:12:26] python profiling failed
Traceback (most recent call last):
  File "/app/gprofiler/main.py", line 272, in _snapshot
    process_profiles.update(future.result())
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/gprofiler/python.py", line 324, in snapshot
    return self._ebpf_profiler.snapshot()
  File "/app/gprofiler/python.py", line 260, in snapshot
    collapsed_path = self._dump()
  File "/app/gprofiler/python.py", line 241, in _dump
    output = self._wait_for_output_file(self.dump_timeout)
  File "/app/gprofiler/python.py", line 233, in _wait_for_output_file
    assert len(output_files) == 1
AssertionError
[15:12:36] Finished running global perf
[15:12:38] Successfully uploaded profiling data to the server
```

**Comment by Jongy** [comment]
Hi @rahulpowar . I think the exception isn't related - this error happens because gProfiler found more than 1 file matching the filename pattern PyPerf writes. There should be one (because PyPerf generates one, we read it and delete it). I added an assert message in https://github.com/Granulate/gprofiler/pull/120 so we can see which files matched the pattern - it might be something unexpected, or a sync issue causing 2 or more files to be written. Until that version is deployed, if this error persists, can you please run `ls` in the container and post here which files are present (it will be `/tmp/gprofiler_tmp/.../pyperf.*.col`).

About the `ERROR_THREAD_STATE_NOT_FOUND` - usually, this is not an error per-se; it means that the profiled thread doesn't have an associated `PyThreadState`. See [here](https://github.com/Granulate/bcc/blob/3d45543714db67172a08d1dffaa84d7c5eb83808/examples/cpp/pyperf/PyPerfBPFProgram.cc#L412). Are the other threads Python-based? If they are purely native threads, they won't have any Python stacks. Were they started via `threading.Thread`? If they were, then it must be a bug in PyPerf :sweat_smile: if that's the case, then should provide us with more information about the app, we'll be able to look more deeply into the issue.

In any case: we are planning to add native stacks collection to PyPerf, so even if Python stacks collection fails, we will see the native stacks (which will immediately tell us if those are Python-based threads or anything else). @YishaiZinkin note :)

**Comment by rahulpowar** [comment]
Thanks @Jongy they are python threads. I think there are about 4 of them all started via a pattern of
```
io = threading.Thread(target=nmsgloop(n,compute), name='XXXX', daemon=True)
io.start()
```
I don't see this functions in the stack so I assume these are the threads rolled up under `ERROR_THREAD_STATE_NOT_FOUND`. This is Python 3.8.5.

**Comment by Jongy** [comment]
I see. Very weird. It's possible that PyPerf's thread iteration is broken - although, we've tested it thoroughly, and I tested now a matching case:
```
Python 3.8.5 (default, May 27 2021, 13:30:53) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.20.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: def th1(): 
   ...:     while 1: 
   ...:         pass 
   ...:                                                                                                                                                                                                    

In [2]: def th2(): 
   ...:     while 2: 
   ...:         pass 
   ...:                                                                                                                                                                                                    

In [3]: import threading                                                                                                                                                                                   

In [4]: threading.Thread(target=th1).start()                                                                                                                                                               

In [5]: threading.Thread(target=th2).start()                                                                                                                                                               

In [6]:                                                                                                                                                                                                    
```

results in this graph:
![Screenshot from 2021-06-24 20-52-45](https://user-images.githubusercontent.com/8831572/123309917-2facd580-d52e-11eb-9e0f-be84417c513f.png)

where you can see the 2 threads.

I will be able to help further if you could share more details about the application - how many threads are there, for how long are they running (very short? or idefinitely?). If possible to share a minimal reproducing example, that'd be best :) you can also send such a sample privately if you don't want to post it publilcy in GH.

**Comment by rahulpowar** [comment]
I suspect the issue is that while it is a Python thread, the native python is quite light and it is mainly calling into Cython that wraps a C lib. So you are right, this might need the native stacks support. Happy to test it when you have an alpha.

**Comment by Jongy** [comment]
Hmm... Cython.. to my understanding, while we'll lack the Cython frames, we should still see at least the first Python frames (of the threading module itself, those bootstrapping a new thread), even if all called code is Cython/native. I will run some tests and post the results here. I'll also let you know here when the native stacks version is in alpha stage, so you can try it out 😄 

Meanwhile, I suggest you to try running the profiler with `--python-mode py-spy`, perhaps py-spy will be able to handle those threads and that'll let you see the Python part of the stacks properly (we don't run py-spy in "native" mode, so no native/Cython; that's something we could add).

**Comment by Jongy** [comment]
I ran a basic test:
```
root@4ff52e35d999:/# cat f.py 
def f1():
    while True:
        pass


def f2():
    while True:
        pass
root@4ff52e35d999:/# cythonize f.py
Compiling /f.py because it changed.
[1/1] Cythonizing /f.py
root@4ff52e35d999:/# gcc -shared -pthread -fPIC -fwrapv -O2 -Wall -fno-strict-aliasing       -I/usr/local/include/python3.8 -o f.so f.c
root@4ff52e35d999:/# mv f.py blabla
root@4ff52e35d999:/# python
Python 3.8.2 (default, Feb 26 2020, 14:58:38) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> import f
>>> import threading
>>> threading.Thread(target=f.f1).start()
```

now, this blocks forever, because unlike Python's opcode loop which, from time to times, gives up the GIL for other threads, Cythonized code doesn't do that.

Anyway, then I ran PyPerf (`v1.0.8`; that's the version used in gProfiler `1.1.2`) and it produces traces as I expected, showing just the Python code from `threading`'s bootstrap:
```
python-1446481/1446543;threading.Thread._bootstrap (/usr/local/lib/python3.8/threading.py:876)_[p];threading.Thread._bootstrap_inner (/usr/local/lib/python3.8/threading.py:915)_[p];threading.Thread.run (/usr/local/lib/python3.8/threading.py:859)_[p] 1
....
```

If you could post more information about your case, I might be able to help further. We'll have the native stacks in a short while and we'll be able to use it, in any case :)

**Comment by Jongy** [comment]
> Happy to test it when you have an alpha.

@rahulpowar , we have merged this feature to master (#132 ), you can try it now (by building the Docker locally) or you can wait for the next release.

**Comment by Jongy** [comment]
[1.1.7](https://github.com/Granulate/gprofiler/releases/tag/1.1.7) was released and it includes the native stacks :)
