### ISSUE TITLE
gProfiler partial DNS resolution error

### ISSUE THREAD

**Issue by akuzkohqs** [Granulate/gprofiler#327]
We have installed gProfiler in Docker containers in both, local (Docker engine, run in EC2 container with unrestricted outgoing connectivity) and remote (AWS Fargate with SYS_PTRACE enabled).

We saw no single metric uploaded in gProfiler dashboard yet.

Docker container base: `node:13.7.0`

Additional commands:
```
RUN apt update && apt install -y curl git && \
    curl -SL https://github.com/Granulate/gprofiler/releases/latest/download/gprofiler --output /tmp/gprofiler && \
    chmod +x /tmp/gprofiler 
```
Startup made from Docker entrypoint:
```
/tmp/gprofiler -cu --token ${GP_PAT} --service-name SERVICE_NAME --disable-pidns-check --perf-mode disabled --no-java --no-python --no-php --no-ruby --nodejs-mode none &
```
We also tried simplified command without any differences, same errors, etc.:
```
/tmp/gprofiler -cu --token ${GP_PAT} --service-name SERVICE_NAME --disable-pidns-check --perf-mode disabled
```

The problem is that while service listed in gProfiler there are massive errors like this:
```
  | 2022-03-29T16:57:06.890+03:00 | [13:57:06] Successfully uploaded profiling data to the server
  | 2022-03-29T16:57:11.902+03:00 | [13:57:11] Failed sending logs to server
  | 2022-03-29T16:57:11.902+03:00 | Traceback (most recent call last):
  | 2022-03-29T16:57:11.902+03:00 | File "urllib3/connectionpool.py", line 449, in _make_request
  | 2022-03-29T16:57:11.902+03:00 | File "<string>", line 3, in raise_from
  | 2022-03-29T16:57:11.902+03:00 | File "urllib3/connectionpool.py", line 444, in _make_request
  | 2022-03-29T16:57:11.902+03:00 | File "http/client.py", line 1346, in getresponse
  | 2022-03-29T16:57:11.902+03:00 | File "http/client.py", line 307, in begin
  | 2022-03-29T16:57:11.902+03:00 | File "http/client.py", line 268, in _read_status
  | 2022-03-29T16:57:11.902+03:00 | File "socket.py", line 586, in readinto
  | 2022-03-29T16:57:11.902+03:00 | File "ssl.py", line 971, in recv_into
  | 2022-03-29T16:57:11.902+03:00 | File "ssl.py", line 833, in read
  | 2022-03-29T16:57:11.902+03:00 | File "ssl.py", line 590, in read
  | 2022-03-29T16:57:11.902+03:00 | socket.timeout: The read operation timed out
  | 2022-03-29T16:57:11.902+03:00 | During handling of the above exception, another exception occurred:
  | 2022-03-29T16:57:11.902+03:00 | Traceback (most recent call last):
  | 2022-03-29T16:57:11.902+03:00 | File "requests/adapters.py", line 449, in send
  | 2022-03-29T16:57:11.902+03:00 | File "urllib3/connectionpool.py", line 786, in urlopen
  | 2022-03-29T16:57:11.902+03:00 | File "urllib3/util/retry.py", line 550, in increment
  | 2022-03-29T16:57:11.902+03:00 | File "urllib3/packages/six.py", line 770, in reraise
  | 2022-03-29T16:57:11.902+03:00 | File "urllib3/connectionpool.py", line 710, in urlopen
  | 2022-03-29T16:57:11.902+03:00 | File "urllib3/connectionpool.py", line 451, in _make_request
  | 2022-03-29T16:57:11.902+03:00 | File "urllib3/connectionpool.py", line 341, in _raise_timeout
  | 2022-03-29T16:57:11.902+03:00 | urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='profiler.granulate.io', port=443): Read timed out. (read timeout=5)
  | 2022-03-29T16:57:11.902+03:00 | During handling of the above exception, another exception occurred:
  | 2022-03-29T16:57:11.902+03:00 | Traceback (most recent call last):
  | 2022-03-29T16:57:11.902+03:00 | File "gprofiler/log.py", line 191, in try_send_log_to_server
  | 2022-03-29T16:57:11.902+03:00 | File "gprofiler/client.py", line 110, in post
  | 2022-03-29T16:57:11.902+03:00 | File "gprofiler/client.py", line 95, in _send_request
  | 2022-03-29T16:57:11.902+03:00 | File "requests/sessions.py", line 542, in request
  | 2022-03-29T16:57:11.902+03:00 | File "requests/sessions.py", line 655, in send
  | 2022-03-29T16:57:11.902+03:00 | File "requests/adapters.py", line 529, in send
  | 2022-03-29T16:57:11.902+03:00 | requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='profiler.granulate.io', port=443): Read timed out. (read timeout=5)
```

We have tested network connectivity and we are able to open profiler.granulate.io using curl and other tools from inside the Docker container(s). Certificate is valid as well.

We may provide additional details if requested.

Thank you for your attention.

**Comment by akuzkohqs** [comment]
@Jongy ...things are changing fast.. Our team gave up with gProfiler ;(
I was able to test things before got "Server error: Invalid API key" as they disabled account.

Btw, thank you for implementing fool-proof protection when all profilers are disabled.

What I found is that Java profiler was giving us a problem like that with /dev/kmsg error (it won't work in Fargate):
```
[06:40:00] Initialized JavaProfiler (frequency: 11hz, duration: 60s)
[06:40:00] Failed to start kernel messages listener. Profilee error monitoring not available. (Do you have permission to read /dev/kmsg?)
Traceback (most recent call last):
  File "gprofiler/kernel_messages.py", line 30, in get_kernel_messages_provider
  File "granulate_utils/linux/devkmsg.py", line 25, in __init__
FileNotFoundError: [Errno 2] No such file or directory: '/dev/kmsg'
[06:40:00] Initialized PythonEbpfProfiler (frequency: 11hz, duration: 60s)
[06:40:00] Python eBPF profiler initialization failed
[06:40:00] Initialized PySpyProfiler (frequency: 11hz, duration: 60s)
[06:40:00] Initialized RbSpyProfiler (frequency: 11hz, duration: 60s)
[06:40:00] Could not find a Docker daemon or CRI-compatible daemon, profiling data will not include the container names. If you do have a containers runtime and it's not supported, please open a new issue here: https://github.com/Granulate/gprofiler/issues/new
[06:40:00] gProfiler initialized and ready to start profiling
[06:40:00] Failed to enable proc_events listener for exited Java processes
Traceback (most recent call last):
  File "granulate_utils/linux/proc_events.py", line 211, in start
PermissionError: [Errno 1] Operation not permitted

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "granulate_utils/linux/ns.py", line 225, in _switch_and_run
  File "granulate_utils/linux/proc_events.py", line 249, in _start_listener
  File "granulate_utils/linux/proc_events.py", line 216, in start
PermissionError: This process doesn't have permissions to bind/connect to the process events connector

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "gprofiler/profilers/java.py", line 848, in start
  File "granulate_utils/linux/proc_events.py", line 261, in wrapper
  File "granulate_utils/linux/ns.py", line 237, in run_in_ns
Exception: run_in_ns execution failed
[06:40:00] Successfully uploaded profiling data to the server
[06:40:00] Stopping ...

```

Then I've tested with "--disable-pidns-check --perf-mode none --no-java"
```
[06:40:15] Initialized PythonEbpfProfiler (frequency: 11hz, duration: 60s)
[06:40:15] Python eBPF profiler initialization failed
[06:40:15] Initialized PySpyProfiler (frequency: 11hz, duration: 60s)
[06:40:15] Initialized RbSpyProfiler (frequency: 11hz, duration: 60s)
[06:40:15] Could not find a Docker daemon or CRI-compatible daemon, profiling data will not include the container names. If you do have a containers runtime and it's not supported, please open a new issue here: https://github.com/Granulate/gprofiler/issues/new
[06:40:15] gProfiler initialized and ready to start profiling
[06:40:15] Successfully uploaded profiling data to the server
```

As you may see no errors. But at the same time still zero samples as well. I was waiting for hour or so.

Hope it helps you to debug it in the future. I highlight that we do have Node.js process in same Docker container and this is what we wished to profile initially.

Let me know if I may help you further while I haven't gProfiler account anymore ;(

**Comment by Jongy** [comment]
I'm sorry to hear that @akuzkohqs :(

About the `/dev/kmsg` & `proc_events` error - these are again false positives, sorry for the confusion (and I will make sure it is addressed) - these are two optional features and the lack of them does not prevent gProfiler from, well, doing its profiling. I will make sure to amend the log messages such that they clarify that profiling is not harmed even if they are present.

Judging by your output logs, I think that my explanation here:

> So the issue that remains is that you're seeing "Successfully uploaded profiling data" but not seeing any data on the server. Just making sure - if running on Fargate with --perf-mode=none, then other profilers for e.g Java/Python must be active, and actually identify processes (otherwise no profiling data is collected, because perf is responsible for collecting data from the entire system).

is what happens. There are no profilers actually running (because `perf` is disabled, and the different runtime profilers do not identify target processes). So gProfiler really uploads empty samples. Which is yet another error condition that we should at least log on, noted this as well.

If it's NodeJS that you want to profile over Fargate - that is sadly not supported yet (as Node is profiled with `perf`, and `perf` is not available on Fargate)

You can actually continue helping me debug even with the account gone, if you'd like :smiley_cat:
* you can either create a new account, or you can run gProfiler with local output flags on your EC2 environment (`-o /tmp/output` instead of `-u`) and inspect the output `.col` file - is it empty or does it contain some samples?
* If it's NodeJS you are trying to profile, make sure to keep perf enabled (i.e no `--no-perf`) and to enable Node perf `--nodejs-mode=perf`, and to enable NodeJS profiling flags on your app: https://github.com/Granulate/gprofiler#nodejs-profiling-options.
* If you're trying to profile Java/python etc, make sure that these processes are identified by gProfiler - you should see a log line "Profiling process ..." for each. If you don't see those lines, then that's definitely an issue and I will need some more details on those processes to implement the fix that'll make gProfiler identify them correctly.
