### ISSUE TITLE
Docker-compose deploy error

### ISSUE THREAD

**Issue by pablodz** [Granulate/gprofiler#368]
Hello there, I added to my docker-compose those lines

```yaml
  gprofiler:
    image: granulate/gprofiler:latest
    restart: always
    container_name: "granulate-gprofiler"
    pid: "host"
    userns_mode: "host"
    privileged: true
    command: '-cu --token "<TOKEN>" --service-name "<SERVICE NAME>"'
```

And then, checking the logs of the container, I see this (I only have golang apps running)

```bash
[17:02:44] Running gProfiler (version 1.2.22), commandline: '-cu --token MYTOKEN --service-name test'[17:02:44] gProfiler arguments: Namespace(app_id_args_filters=[], application_metadata=True, collect_metadata=True, collect_metrics=True, config=None, container_names=True, continuous=True, controller_pid=None, duration=60, flamegraph=True, frequency=11, identify_applications=True, java_async_profiler_args=None, java_async_profiler_buildids=False, java_async_profiler_mode='auto', java_async_profiler_safemode=64, java_jattach_timeout=30, java_mode='ap', java_safemode='profiled-oom,profiled-signaled,hserr', java_version_check=True, log_file='/var/log/gprofiler/gprofiler.log', log_rotate_backup_count=1, log_rotate_max_size=5242880, log_to_server=True, log_usage=False, nodejs_mode='disabled', output_dir=None, perf_dwarf_stack_size=8192, perf_inject=False, perf_mode='fp', php_mode='disabled', php_process_filter='php-fpm', pid_ns_check=True, profile_api_version=None, python_add_versions=True, python_mode='auto', python_pyperf_user_stacks_pages=None, rotating_output=False, ruby_mode='rbspy', server_host='https://profiler.granulate.io', server_token='MYTOKEN', server_upload_timeout=120, service_name='test', upload_results=True, verbose=False)
[17:02:44] gProfiler Python version: 3.8.10 (default, Mar 15 2022, 12:22:08)
[GCC 9.4.0]
[17:02:44] gProfiler deployment mode: container[17:02:44] Kernel uname release: 3.10.0-1160.53.1.el7.x86_64[17:02:44] Kernel uname version: #1 SMP Fri Jan 14 13:59:45 UTC 2022[17:02:44] Total CPUs: 2[17:02:44] Total RAM: 0.94 GB[17:02:44] Linux distribution: CentOS Linux | 7 | Core[17:02:44] libc version: glibc-2.17
[17:02:44] Hostname: ip-10-4-0-235
[17:02:44] The connection to the server was successfully established (service 'test')
[17:02:44] Initialized JavaProfiler (frequency: 11hz, duration: 60s)
[17:02:45] Initialized SystemProfiler (frequency: 11hz, duration: 60s)
[17:02:45] Initialized PythonEbpfProfiler (frequency: 11hz, duration: 60s)
[17:02:45] Python eBPF profiler initialization failed
[17:02:45] Initialized PySpyProfiler (frequency: 11hz, duration: 60s)
[17:02:45] Initialized RbSpyProfiler (frequency: 11hz, duration: 60s)
[17:02:45] Discovered container runtimes: ['docker']
[17:02:45] gProfiler initialized and ready to start profiling
[17:02:45] Starting perf (fp mode)
[17:02:45] Started perf (fp mode)
[17:02:45] Profiling process 1324 with py-spy (cmdline=['/usr/sbin/asterisk', '-f', '-vvvg', '-c'])
[17:02:45] Profiling process 901 with py-spy (cmdline=['/usr/bin/python2', '-Es', '/usr/sbin/tuned', '-l', '-P'])
[17:02:46] PySpyProfiler: failed to profile process 1324 (asterisk)
Traceback (most recent call last):
  File "/app/gprofiler/profilers/profiler_base.py", line 139, in snapshot
    result = future.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/gprofiler/profilers/python.py", line 210, in _profile_process
    run_process(
  File "/app/gprofiler/utils/__init__.py", line 265, in run_process
    raise CalledProcessError(retcode, process.args, output=stdout, stderr=stderr)
gprofiler.exceptions.CalledProcessError: Command '['/app/gprofiler/resources/python/py-spy', 'record', '-r', '11', '-d', '60', '--nonblocking', '--format', 'raw', '-F', '--gil', '--output', '/tmp/gprofiler_tmp/tmptu1pou4f/pyspy.fRfoYMMoamRizEDV.1324.col', '-p', '1324', '--full-filenames']' returned non-zero exit status 1.
stdout: b''
stderr: b'Error: Failed to find python version from target process\n\n'
```

**Comment by pablodz** [comment]
I changed to

```yaml
gprofiler:
        image: granulate/gprofiler:latest
        restart: always
        container_name: "granulate-gprofiler"
        pid: "host"
        userns_mode: "host"
        privileged: true
        command: '-cu --token "MYTOKEN" --service-name "test" --no-java --no-python --no-php --no-ruby '
```
And now works

**Comment by Jongy** [comment]
Hi @pablodz , the error you were seeing is the Python profiler failing to profile certain processes. While this is an issue by itself (we expect py-spy to successfully profile all Python applications), this doesn't affect the profiling of other processes, it only clutters the logs with these errors :sweat_smile: 
Nonetheless, your solution is fine - if you don't care about profiling Java, Python etc then you can add those flags to avoid running e.g py-spy at all, and then you won't see those errors.

I suppose asterisk is [this](https://wiki.asterisk.org/wiki/display/AST/Running+Asterisk) project? this appears to be a daemon and not an app we'd want to profile, but I will check anyway if it's truly a Python-based app, and if so, why py-spy fails to profile it.

**Comment by pablodz** [comment]
Yes, asterisk is a daemon running outside docker compose in the instance, I don't want to profile that C application
