### ISSUE TITLE
Support for php on arm64 ?

### ISSUE THREAD

**Issue by pesseyjulien** [Granulate/gprofiler#429]
Hi,

Do you plan on supporting php for arm64 ?

Best,
Julien

**Comment by Jongy** [comment]
Hi @pesseyjulien ,

phpspy doesn't claim to support Aarch64. [I opened a ticket](https://github.com/adsr/phpspy/issues/122) and we'll keep progress there, I think that I'll try to build it now and see. If does build & work - then adding it to the Aarch64 build of gProfiler is easy.

**Comment by Jongy** [comment]
Will be supported in the next release :) See https://github.com/Granulate/gprofiler/pull/430

**Comment by pesseyjulien** [comment]
Hi,

I tried the latest release on my aws fargate ecs and here is what I'm getting :

```
[08:17:02] Failed to start kernel messages listener. Profilee error monitoring via kernel messages is not available (this does not prevent profiling). Do you have permission to read /dev/kmsg?
Traceback (most recent call last):
  File "gprofiler/kernel_messages.py", line 33, in get_kernel_messages_provider
  File "granulate_utils/linux/devkmsg.py", line 25, in __init__
FileNotFoundError: [Errno 2] No such file or directory: '/dev/kmsg'
[08:17:02] Initialized PySpyProfiler (frequency: 11hz, duration: 60s)
[08:17:02] Initialized RbSpyProfiler (frequency: 11hz, duration: 60s)
[08:17:02] Could not find a Docker daemon or CRI-compatible daemon, profiling data will not include the container names. If you do have a containers runtime and it's not supported, please open a new issue here: https://github.com/Granulate/gprofiler/issues/new
[08:17:02] gProfiler initialized and ready to start profiling
[08:17:02] Failed to enable proc_events listener for exited Java processes (this does not prevent Java profiling)
Traceback (most recent call last):
  File "granulate_utils/linux/proc_events.py", line 211, in start
PermissionError: [Errno 1] Operation not permitted

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "granulate_utils/linux/ns.py", line 248, in _switch_and_run
  File "granulate_utils/linux/proc_events.py", line 249, in _start_listener
  File "granulate_utils/linux/proc_events.py", line 216, in start
PermissionError: This process doesn't have permissions to bind/connect to the process events connector

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "gprofiler/profilers/java.py", line 1054, in start
  File "granulate_utils/linux/proc_events.py", line 261, in wrapper
  File "granulate_utils/linux/ns.py", line 263, in run_in_ns
Exception: run_in_ns execution failed
```

I did add the SYS_PTRACE capability.

I know the support for arch64 is still in beta, so If it can help.

Best,
Julien

**Comment by Jongy** [comment]
@pesseyjulien those 2 feautres that you get error for are auxliary - gProfiler reads additional diagnostics data (kernel messages and PIDs starting/exiting). Both don't harm the profiling - gProfiler just won't have this additional data (the error messages read `this does not affect profiling`)

phpspy should work just fine regardless :)

**Comment by pesseyjulien** [comment]
Ok, sorry I missed the message.. That being said, I dont see any data on the dashboard while the profiler seems to be sending data :

[08:52:01] Successfully uploaded profiling data to the server

**Comment by Jongy** [comment]
You are running gProfiler on Fargate, so `perf` is disabled and only samples from runtime processes are collected (instead of system wide).
No samples in the dashboard probably means no data is collected by runtime profilers.

Reminding that php is disabled by default (enable with `--php-mode=phpspy`) and you might also require to change `--php-process-filter` (defaults to `php-fpm`).

**Comment by pesseyjulien** [comment]
thanks !

**Comment by pesseyjulien** [comment]
yes It helped with `--php-mode=phpspy`, did not change the process filter as I'm running php-fpm.
