### ISSUE TITLE
nodejs: attach-maps: /tmp/perf-pid.map file missing on cleanup

### ISSUE THREAD

**Issue by Jongy** [Granulate/gprofiler#537]
See example test failure: https://github.com/Granulate/gprofiler/actions/runs/3243777862/jobs/5320303422

What happens is - it seems that attach failed and we never enabled the perf.map DSO. Thus, no file is created and we get this error upon cleanup:
```
[2022-10-13 17:29:53,900] WARNING: gprofiler.profilers.node: Could not clean up debug symbols for pid 22987. Reason: [Errno 2] No such file or directory: '/tmp/perf-8.map'
Traceback (most recent call last):
  File "/app/gprofiler/profilers/node.py", line 230, in clean_up_node_maps
    run_in_ns(
  File "/usr/local/lib/python3.8/dist-packages/granulate_utils/linux/ns.py", line 261, in run_in_ns
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/granulate_utils/linux/ns.py", line 248, in _switch_and_run
    ret = callback()
  File "/app/gprofiler/profilers/node.py", line 232, in <lambda>
    lambda: _clean_up(dest, nspid, ns_link_name),
  File "/app/gprofiler/profilers/node.py", line 192, in _clean_up
    os.remove(os.path.join("/tmp", f"perf-{nspid}.map"))
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/perf-8.map'
```

We can either:
1. Ignore the file missing - I don't like it much, I prefer the code to be explicit, if we expect the file to be there, then it should really be there
2. Fix code to avoid trying to remove the file if we don't know that it was created (i.e, if we encountered errors during the attach process, then obv the file won't be created, so don't try removing it).

**Comment by Jongy** [comment]
We implemented option 2
