### ISSUE TITLE
tests: nodejs: flaky failure in attach-maps

### ISSUE THREAD

**Issue by Jongy** [Granulate/gprofiler#584]
https://github.com/Granulate/gprofiler/actions/runs/3409188507/jobs/5670935985

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/granulate_utils/linux/ns.py", line 248, in _switch_and_run
    ret = callback()
  File "/home/runner/work/gprofiler/gprofiler/gprofiler/metadata/versions.py", line 27, in _run_get_version
    return run_process([exe_path, version_arg], stop_event=stop_event, timeout=get_version_timeout)
  File "/home/runner/work/gprofiler/gprofiler/gprofiler/utils/__init__.py", line 278, in run_process
    raise reraise_exc
gprofiler.exceptions.CalledProcessTimeoutError: Timed out after 3 seconds
Command '['/proc/1/exe', '--version']' died with <Signals.SIGKILL: 9>.
stdout: b''
stderr: b''
```

Do we run the app with limits?

**Comment by mpozniak95** [comment]
The same issue here: https://github.com/Granulate/gprofiler/actions/runs/3417688664/jobs/5689483196
