### ISSUE TITLE
dotnet: test_executable_not_privileged failure

### ISSUE THREAD

**Issue by Jongy** [Granulate/gprofiler#697]
Example run: https://github.com/Granulate/gprofiler/actions/runs/4217195658/jobs/7321069929

Failure:
```
E       Provider Name                           Keywords            Level               Enabled By
E       Microsoft-DotNETCore-SampleProfiler     0x0000F00000000000  Informational(4)    --profile 
E       Microsoft-Windows-DotNETRuntime         0x00000014C14FCCBD  Informational(4)    --profile 
E       
E       Process        : Process1
E       Output File    : /tmp/gprofiler_tmp/tmp3o1y169p/dotnet-trace-hkYnZMwctShckhRe-1
E       Trace Duration : 00:00:01:00
E       
E       
E       
E       Stopping the trace. This may take several minutes depending on the application being traced.
E       
E       Trace completed.
E       Writing:	/tmp/gprofiler_tmp/tmp3o1y169p/dotnet-trace-hkYnZMwctShckhRe-1.speedscope.json
E       System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Http, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
E       
E       File name: 'System.Net.Http, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
E          at Microsoft.Diagnostics.Tools.Trace.TraceFileFormatConverter.Convert(TraceFileFormat format, String fileToConvert, String outputFilename, Boolean continueOnError)
E          at Microsoft.Diagnostics.Tools.Trace.TraceFileFormatConverter.ConvertToFormat(TraceFileFormat format, String fileToConvert, String outputFilename)
E       Conversion complete
E       )
```

Underlying error: `System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Http, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.`.

**Comment by Jongy** [comment]
@pfilipko1 can you please take a look?
